#!/usr/bin/env python3
"""
Analyze error-shift composition across SFT runs.

Expected input:
- manifest jsonl generated by run_train_eval_matrix.sh
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Dict, List, Tuple


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Build error-shift analysis report from run manifest.")
    p.add_argument("--manifest_jsonl", type=str, required=True)
    p.add_argument("--output_md", type=str, required=True)
    p.add_argument("--output_json", type=str, required=True)
    p.add_argument("--close_gap_threshold", type=float, default=0.01)
    return p.parse_args()


def _load_manifest(path: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def _load_eval_rows(path: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def _classify_error_case(row: Dict[str, Any]) -> str:
    # local mirror of finqa_baseline/utils/io.py to avoid path coupling.
    raw = str(row.get("raw_output", "")).lower()
    gold = row.get("gold")
    pred = row.get("pred")

    if row.get("pred") is None:
        return "parse fail"
    if "%" in raw:
        return "percent scaling"
    unit_hints = ["million", "billion", "thousand", "k", "m", "bn", "usd", "dollar", "kg", "ton"]
    if any(h in raw for h in unit_hints):
        return "unit confusion"
    try:
        if pred is not None and gold is not None and abs(float(pred) - float(gold)) > 1e-3:
            return "numeric mismatch"
    except Exception:
        return "numeric mismatch"
    return "numeric mismatch"


def _compute_stats(rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    total = len(rows)
    n_correct = sum(1 for r in rows if bool(r.get("correct")))
    n_parse_fail = sum(1 for r in rows if bool(r.get("parse_fail")))

    wrong = [r for r in rows if not bool(r.get("correct"))]
    buckets: Counter[str] = Counter()
    for r in wrong:
        buckets.update([_classify_error_case(r)])

    bucket_rate = {k: (v / len(wrong) if wrong else 0.0) for k, v in buckets.items()}
    return {
        "num_samples": total,
        "accuracy": (n_correct / total) if total else 0.0,
        "parse_fail_rate": (n_parse_fail / total) if total else 0.0,
        "num_wrong": len(wrong),
        "error_bucket_counts": dict(buckets),
        "error_bucket_rates": bucket_rate,
    }


def _merge_run(manifest_row: Dict[str, Any]) -> Dict[str, Any]:
    eval_jsonl = Path(str(manifest_row.get("eval_jsonl", "")))
    if not eval_jsonl.exists():
        raise FileNotFoundError(f"eval_jsonl not found: {eval_jsonl}")
    stats = _compute_stats(_load_eval_rows(eval_jsonl))
    out = dict(manifest_row)
    out.update(stats)
    return out


def _pairwise_style(runs: List[Dict[str, Any]], close_gap_threshold: float) -> List[Dict[str, Any]]:
    grouped: Dict[Tuple[str, str], Dict[str, Dict[str, Any]]] = defaultdict(dict)
    for r in runs:
        style = str(r.get("supervision_style", ""))
        if style not in {"answer_only", "formula_rationale"}:
            continue
        key = (str(r.get("model_size", "")), str(r.get("train_size", "")))
        grouped[key][style] = r

    pairs: List[Dict[str, Any]] = []
    for (model_size, train_size), cell in sorted(grouped.items(), key=lambda x: (x[0][0], x[0][1])):
        if "answer_only" not in cell or "formula_rationale" not in cell:
            continue
        a = cell["answer_only"]
        b = cell["formula_rationale"]
        delta = float(b["accuracy"]) - float(a["accuracy"])

        categories = sorted(
            set(a.get("error_bucket_rates", {}).keys()) | set(b.get("error_bucket_rates", {}).keys())
        )
        bucket_delta = {}
        for cat in categories:
            br = float(b.get("error_bucket_rates", {}).get(cat, 0.0))
            ar = float(a.get("error_bucket_rates", {}).get(cat, 0.0))
            bucket_delta[cat] = br - ar

        pairs.append(
            {
                "model_size": model_size,
                "train_size": train_size,
                "acc_answer_only": float(a["accuracy"]),
                "acc_formula_rationale": float(b["accuracy"]),
                "delta_formula_minus_answer": delta,
                "close_score_gap": abs(delta) < close_gap_threshold,
                "error_rate_delta_formula_minus_answer": bucket_delta,
            }
        )
    return pairs


def _to_markdown(payload: Dict[str, Any]) -> str:
    runs = payload["runs"]
    pairs = payload["pairwise_style"]
    close_gap_threshold = payload["close_gap_threshold"]

    lines: List[str] = []
    lines.append("# Error Shift Analysis")
    lines.append("")
    lines.append("## Run Summary")
    lines.append(
        "| run_name | model_size | train_size | supervision_style | n | acc | parse_fail_rate | wrong_n |"
    )
    lines.append("|---|---|---|---|---:|---:|---:|---:|")
    for r in runs:
        lines.append(
            f"| {r.get('run_name','')} | {r.get('model_size','')} | {r.get('train_size','')} | "
            f"{r.get('supervision_style','')} | {int(r.get('num_samples',0))} | "
            f"{float(r.get('accuracy',0.0)):.6f} | {float(r.get('parse_fail_rate',0.0)):.6f} | "
            f"{int(r.get('num_wrong',0))} |"
        )

    lines.append("")
    lines.append("## Style Comparison: answer_only vs formula_rationale")
    lines.append(
        f"- close-score threshold: {close_gap_threshold:.4f} (if |delta| below threshold, use error composition as primary signal)"
    )
    lines.append(
        "| model_size | train_size | acc_answer_only | acc_formula_rationale | delta_formula_minus_answer | close_score_gap |"
    )
    lines.append("|---|---|---:|---:|---:|---|")
    for p in pairs:
        lines.append(
            f"| {p['model_size']} | {p['train_size']} | {p['acc_answer_only']:.6f} | "
            f"{p['acc_formula_rationale']:.6f} | {p['delta_formula_minus_answer']:.6f} | "
            f"{p['close_score_gap']} |"
        )

    lines.append("")
    lines.append("### Error Composition Delta (formula_rationale - answer_only)")
    for p in pairs:
        lines.append(f"- {p['model_size']} / {p['train_size']}: {json.dumps(p['error_rate_delta_formula_minus_answer'], ensure_ascii=False)}")

    return "\n".join(lines) + "\n"


def main() -> None:
    args = parse_args()
    manifest_rows = _load_manifest(Path(args.manifest_jsonl))
    runs = [_merge_run(r) for r in manifest_rows if Path(str(r.get("eval_jsonl", ""))).exists()]
    runs.sort(key=lambda r: (str(r.get("model_size", "")), str(r.get("train_size", "")), str(r.get("supervision_style", ""))))

    pairs = _pairwise_style(runs, close_gap_threshold=float(args.close_gap_threshold))
    payload = {
        "close_gap_threshold": float(args.close_gap_threshold),
        "runs": runs,
        "pairwise_style": pairs,
    }

    output_json = Path(args.output_json)
    output_json.parent.mkdir(parents=True, exist_ok=True)
    with output_json.open("w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)

    output_md = Path(args.output_md)
    output_md.parent.mkdir(parents=True, exist_ok=True)
    with output_md.open("w", encoding="utf-8") as f:
        f.write(_to_markdown(payload))

    print(f"[saved] {output_md}")
    print(f"[saved] {output_json}")


if __name__ == "__main__":
    main()

